name: Publish Docker image
on:
  push:
    branches: [ polytracker ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Release, Debug]
    steps:
      - name: Set Docker image tag
          id: setTag
          run: |
            if [[ "${{ matrix.build_type }}" == "Debug" ]]; then
                echo "::set-output name=dockerTag::debug-"
            else
                echo "::set-output name=dockerTag::"
            fi
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}
          tags: trailofbits/polytracker-llvm:${{ steps.setTag.outputs.dockerTag }}latest,trailofbits/polytracker-llvm:${{ steps.setTag.outputs.dockerTag }}${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
